title: Transect-level data, 20 m buffer
description: Dataset contains LAI, CHM, and VSWC data collected at 83 transects of varying canopy conditions.

publisher_text: Q. Qin
publisher_url: https://www.researchsquare.com/article/rs-4287919/v1
